{{< include _includes/_front_matter.qmd >}}
{{< include _includes/_init_fontawesome.qmd >}} 
{{< include _includes/_katex_macros.qmd >}} 
{{< include _includes/_r_themes.qmd >}}
<!-- {{< include _includes/_r_rating_init.qmd >}} -->

<!-- {{< include _level_1.qmd >}} -->
<!-- {{< include _level_2.qmd >}} -->
<!-- {{< include _level_3.qmd >}} -->

<!-- {{< include _includes/_r_rating.qmd >}} -->

## Verbrennung 

Die Verbrennung ist ein chemischer Prozess, bei dem eine Ausgangssubstanz durch Sauerstoff zersetzt wird. Dabei wird die innere Energie der Ausgangssubstanz in Wärme und Licht umgewandelt und die Ausgangssubstanz selbst in gasförmige Bestandteile umgewandelt. Die Hauptreaktion ist die Oxidation einiger oder aller Atome der ursprünglichen Verbindung. Die gasförmigen Produkte sind bei einer vollständigen Verbrennung die entsprechenden Oxide der Elemente.

### Bedeutung der Verbrennung

Der Mensch nutzt die Verbrennung seit Jahrtausenden für Nahrungszubereitung, bei der durch das Feuer Nährstoffe in verdaubarer Form umgewandelt werden. Feuer spendet jedoch auch Licht und dadurch Schutz vor Kälte und Wildtieren. Die Verbrennung ist jedoch auch die Grundlage der technischen Entwicklung der Menschheit. Daneben kann sie auch deren Untergang sein durch die exzessive Verbrennung von organischen Stoffen, die seit Jahrmillionen als fossile Energieträger unter der Erde liegen.

Alleine wegen den Abgasen und dem Rauch, werden viele Verbrennungsprozesse immer in Kontakt mit der Atmosphäre gefahren. Das heisst sie finden bei Atmosphärendruck statt und von daher bei konstantem Druck abläuft. Dadurch ist die Enthalpie die entscheidende thermodynamische Grösse, die die Verbrennung nützlich charakterisiert.

Das Ergebnis der Verbrennung ist eine bisweilen heftige exotherme Reaktion bei der eine Menge Hitze entsteht.

### Brennen der Hauptelemente des Lebens 

Wir konzentrieren uns auf diejenigen chemischen Elementen, die am häufigsten in lebender Materie vorkommen. Im menschlichen Körper machen die CHNOPS Elementen 99% der Gesamtmasse aus. 

#### Kohlenstoff

Verbrennen wir **Kohlenstoff** zuerst

$$
\ce{C(s) + O2(g) -> CO2(g)}. 
$$

Kohlenstoff verbrennt bei genügend Sauerstoff immer zu $\ce{CO2}$. Ist relativ weniger Sauerstoff vorhanden, dann entsteht auch das gefährliche $\ce{CO}$.

#### Wasserstoff

**Wasserstoff** verbrennt in der *Knallgasreaktion* 

$$
\ce{H2(s) + 1/2 O2(g) -> H2O(l)}, 
$$

wobei Du beachten solltest, dass das Produkt Wasser am Ende flüssig vorliegt. Wir werden später erläutern, warum das hier wichtig ist.

#### Stickstoff

**Stickstoff** reagiert erst bei höheren Temperaturen mit Sauerstoff und ist neben natürlichen Quellen als Beiprodukt von Verbrennungen vorhanden. Die Produkte sind Stickstoffoxid $\ce{NO}$ und Stickstoffdioxid $\ce{NO2}$. Die Entstehung der Stickoxide ist recht kompliziert. In der Biologie liegt der Stickstoff in den meisten Fällen als Aminogruppe an einem Kohlenstoffatom gebunden vor; zum Beispiel wie hier

$$
\ce{{Molekül}-CH2-NH2}.
$$

Die Striche in der Struktur stellen kovalente Bindungen dar. Von daher ist die Verbrennung von Ammoniak

$$
\ce{2 NH3(g) + 3/2 O2(g) -> N2(g) + 3 H2O(l)} 
$$

eher von Interesse. 

#### Phosphor

**Phosphor** verbrennt als weisser Phosphor zu $\ce{P4O10}$. Das ist aber nicht weiter interessant für die Biologie, da Phosphor in biologischen Makromoleküle immer oxidiert vorliegt.

#### Schwefel

Der **Schwefel** liegt in biologischen Makromolekülen ähnlich vor wie der Stickstoff

$$
\ce{{Molekül}-CH2-SH}.
$$

Auch hier stehen die horizontalen Striche für kovalente Bindungen. Diese $\ce{SH}$ Gruppe hat absolute Ähnlichkeit zu einer Alkoholgruppe. Solche Verbindungen heissen Thiole statt Alkohole. Elementarer Schwefel verbrennt zuerst zu Schwefeldioxid in einem Anfangsschritt

$$
\ce{H2S(g) + 3/2 O2(g) -> SO2(g) + H2O(l)},
$$ {#eq-sulfur-combustion}

der Ähnlichkeit zur Kohlenstoffverbrennung hat. Allerdings folgt oft eine zweiter Schritt. Einerseits kann elementarer Schwefel wie im Claus Prozess nach der Gleichung

$$
\ce{2 H2S(g) + SO2(g) -> 3 S(s) + 2 H2O(l)}
$$

gebildet werden. Das sieht wiederum in der Summe wie die Verbrennung von Ammoniak aus. Andererseits kann auch eine weitere Oxidation nach der Gleichung 

$$
\ce{SO2(g) + 1/2 O2(g) -> SO3(g)}
$$

erfolgen. Dann haben wir eher etwas, was wie die Kohlenstoffverbrennung aussieht. Wir werden aufgrund dieser unterschiedlichen Reaktionsmöglichkeiten nur @eq-sulfur-combustion anwenden. 

### Verbrennen organischer Materie

Wenn organische Materie verbrannt wird, dann schauen wir bevorzugt auf die Elemente $\ce{CHNOS}$. Diese decken immer noch mehr als 85% der Biomasse ab. Die allgemeine Reaktionsgleichung kann so geschrieben werden:

$$
\ce{{Biomasse} + x O2(g) -> a CO2(g) + b H2O(l) + c N2(g) + d SO2(g)}.
$$ {#eq-biomass-combustion}

Hierbei entsprechen alle Aggregatzustände dem Standardzustand. Mit diesen Elementen können alle biologischen Stoffklassen, die auch als Nahrung dienen, gebaut werden. Dazugehören die Kohlenhydrate, die Fette,und die Proteine. Lediglich die DNA besitzt einen nennenswerten Anteil an Phosphor.

## Technische Verbrennung

### Heizwert

Verbrennen wir das Gas Methan an der Luft. Methan ist ein Treibstoff, das durch Biogasanlagen produziert wird. Die Verbrennung läuft folgendermassen ab:

$$
\ce{CH4(g) + 2O2(g) -> CO2(g) + 2 H2O(g)},\;\Delta H_{\text{c},n}^{\circ} = -802\,\small\kilojoulepermole. 
$$ {#eq-methane}

Beachte, dass wir das Wasser im gasförmigen Zustand haben; so läuft das ja auch ab unter freiem Himmel.  

Die Verbrennungsenthalpie $\Delta H_{\text{c},n}^{\circ}$ nennen wir den **Heizwert**. Die Enthalpie hat einen Index **c**; das ist der Anfangsbuchstabe des englischen Wortes für Verbrennung *combustion*. Der index $n$ bedeutet, dass wir die Enthalpie auf Stoffmenge beziehen. Auf Masse bezogen sind es $\Delta H_{\text{c},m}^{\circ} = -50\,\kilojoulepermole$. Diese Enthalpie stellt die bei konstantem Druck verwertbare Wärmeenergie der Verbrennung laut

$$
\Delta H_{\text{c},n}^{\circ} = \Delta U_{\text{c},n} - p \Delta V_n
$$

dar. Beachte, dass wir in dieser Gleichung alle Größen auf Stoffmenge beziehen, selbst das Volumen $V_n$. Das sind molare Größen. Das molare Volumen ist bei $T = 298\,\kelvin$ etwa $V_n = 0.0245\cubicmeterpermole$, wenn wir ein perfektes Gase annehmen. Dadurch ist das molare Volumen auch nicht abhängig von der Substanz und gilt für alle Gase. Die Gleichung sagt aus, dass die verwertbare Energie **nicht** der inneren Energie des Brennstoffs entspricht, da die Gase in diesem Fall Expansionsarbeit $W_n = -p \Delta V_n$ leisten.

Beim Camping oder beim Kochen mit Gas verwenden wir Propan oder Butan. Propan verbrennt im Campingkocher so

$$
\ce{C3H8(g) + 5 O2(g) → 3 CO2(g) + 4 H2O(g)},\;\Delta H\sub{c,n}^{\circ} = −2044\,\small\kilojoulepermole. 
$$

Die Standardenthalpie pro Masse ist $\Delta H_{\text{c},m}^{\circ} = -46\,\kilojoulepermole$. 

Isooctan ist eines der Komponenten bei der Oktanskala von Treibstoffen. Die Oktanskala zeigt an wieviel Kompression ein Treibstoff verkraften kann, bevor es anfängt im Motor zu klopfen. Das Verbrennen von Isooctane funktioniert nach folgendem Schema

$$
\ce{C8H18(l) + 25/2 O2(g) -> 8 CO2(g) + 9 H2O(l)},\;\Delta H_{\text{c},n}^{\circ} = −5055\,\small\kilojoulepermole,
$$

wobei die entstandene Energie pro Masse $\Delta H_{\text{c},m}^{\circ} = -44\,\kilojoulepermole$.

### Brennwert - Wasserrückgewinnung

Wenn Verbrennungsenthalpien bestimmt werden, dann handelt es sich um Standardenthalpien. Wie Du weisst, werden diese bei $p = 101325\,\pascal$ und $T = 298\,\kelvin$ gemessen. Das heisst aber, dass alle Produkte nach der Verbrennung in ihren Standardzustand zurückgeführt werden. Dabei geschieht folgendes 

$$
\ce{H2O(g) -> H2O(l)},\;-\Delta H_{\text{vap},n}^{\circ} = -45\,\small\kilojoulepermole.
$$ {#eq-water-condensation}

Das Vorzeichen hat sich umgedreht und das bedeutet, dass bei der Kondensation, der Umkehrung des Verdampfens, Energie frei wird. Diese müssten wir zu @eq-methane dazu rechnen. Wie geht das? Ganz einfach, man zählt @eq-methane und @eq-water-condensation zusammen:

$$
\ce{CH4(g) + 2 O2(g) +} \xcancel{\ce{H2O(g)}} \ce{-> CO2(g) +} \xcancel{\ce{H2O(g)}} \ce{+ H2O(l)}. 
$$ 

Dabei mussten wir @eq-water-condensation mit der Zahl Zwei multiplizieren, weil in @eq-methane zwei Moleküle Wasser entstehen. Nach Wegstreichen der Substanzen, die auf beiden Seiten gleich sind, ergibt sich

$$
\ce{CH4(g) + 2 O2(g) -> CO2(g) + 2 H2O(l)}. 
$$ 

Die Verbrennungsenthalpie oder der Brennwert dieser Reaktion ist

$$
\begin{split}
\Delta H_{\text{c},m}^{\circ} 
    &= \Delta H_{\text{c},n}^{\circ} + 2 \cdot \left( - \Delta H_{\text{vap},n}^{\circ} \right) \\
    &= -802\,\small\kilojoulepermole - 2 \cdot 45\,\small\kilojoulepermole \\
    &= -892\,\small\kilojoulepermole, 
\end{split}
$$

und dadurch höher als bei der Verbrennung bei dem das Wasser nicht zurück gewonnen wird. Je mehr Wasser bei der Verbrennung entsteht, desto größer ist die verlorene Energie durch das Entweichen des Dampfes. 

### Messung von schwefelhaltigen Verbindungen

Bei der Messung der Verbrennungsenthalpie von schwefelhaltigen Substanzen ergeben sich einige Schwierigkeiten. Die Verbrennung von schwefelhaltigen Substanzen erfolgt in einem rotierenden Kalorimeter. So wird das entstehende $\ce{SO3}$ mit vorhandenem Wasser zu Schwefelsäure $\ce{H2SO4}$ umgesetzt. Wir schauen uns die Reaktionen genauer an. Zuerst erfolgt die weitere Oxidation von Schwefeldioxid zu Schwefeltrioxid

$$
\ce{SO2(g) + O2(g) -> SO3(g)},\;\Delta H_{\text{r},n,1}^{\circ} = -98\,\small\kilojoulepermole.
$$ {#eq-sulfur-dioxide-oxidation}

Das kleine "r" Index steht für Reaktion. Aus Schwefeltrioxid und Wasser entsteht dann Schwefelsäure 

$$
\ce{SO3(g) + H2O(l) -> H2SO4(l)},\;\Delta H_{\text{r},n,2}^{\circ} = -175\,\small\kilojoulepermole.
$$

Daraus ergibt sich die Gesamtreaktion

$$
\ce{SO2(g) + O2(g) + H2O(l) -> H2SO4(l)}
$$

mit der Reaktionsenthalpie

$$
\begin{split}
\Delta H_{\text{r},n}^{\circ}\left(\ce{H2SO4}\right) &= \Delta H_{\text{r},n,1}^{\circ} + \Delta H_{\text{r},n,2}^{\circ} \\
&= -98\,\small\kilojoulepermole + \left(-175\,\small\kilojoulepermole \right) \\
&= -273\,\small\kilojoulepermole.
\end{split}
$$ {#eq-sulfuric-acid-from-sulfur-dioxide}

Alle Verbrennungsenthalpien von schwefelhaltigen Verbindungen haben die Schwefelsäure als ein Endprodukt. Wenn die reine Verbrennungsreaktion betrachtet wird, dann ist die Verbrennungsenthalpie um den Betrag von $-273\,\small\kilojoulepermole$ höher als die Verbrennungsenthalpie, die zu Schwefeldioxid führt.

## Stoffwechsel

Der Stoffwechsel führt formal gesehen ebenfalls eine Verbrennung aus. Allerdings unterschiedet die sich von der technischen und physikalischen Verbrennung in folgenden Punkten:

- Die Stoffwechselverbrennung teilt die Energiegewinnung in kleine Schritte ein, sonst würde die Zelle durch die eigenen Energiegewinnung verbrennen.
- Das Verbrennungsprodukt Wasser liegt immer als Flüssigkeit vor. Dadurch steht grundsätzlich mehr Energie zur Verfügung als beim Lagerfeuer unter freiem Himmel.
- Es findet keine vollständige Verbrennung bezüglich des Stickstoffs statt, weil das Leben den Stickstoff als organische Verbindung ausscheidet. Dadurch geht wiederum ein Teil der Verbrennungsenergie verloren.
- In der technischen Verbrennung wird alles Organische verbrannt; Tatsache ist, dass viele Faserstoffe gar nicht verdaut werden können. 

Dadurch nennen wir die Verbrennung im Stoffwechsel eine Verstoffwechselung oder Metabolisiserung, um sie von der technischen Verbrennung zu unterscheiden. 

Wir betrachten jetzt die metabolische Verbrennung von drei der vier Klassen von biologischen Makromolekülen, die als Nahrungsquelle dienen. Das sind die Kohlenhydrate, die Fette und die Proteine. Die Verbrennung von DNA lassen wir aus, da sie in der Nahrung nur einen sehr kleinen Anteil ausmacht. Auch Proteine dienen eher als Baustoff und nur dann als Energiequelle, wenn die Kohlenhydrate und Fette bereits verbraucht sind.

### Zucker

Der klassische Fall ist die Verstoffwechselung von Glucose. Die Reaktion sieht so aus

$$
\begin{gather*}
\ce{C6H12O6(s) + 6 O2(g) -> 6 CO2(g) + 6 H2O(l)}\\
\Delta H\sub{metab,\mathnormal{n},Glucose}^{\circ} = -2805\,\small\kilojoulepermole.
\end{gather*}
$$ {#eq-glucose-combustion}

Fructose, die ebenfalls ein Zucker ist und dieselbe Summenformel wie Glucose hat, wird fast mit derselben Enthalpie meabolisiert. Die Ribose, ein Fünffachzucker, der in der DNA vorkommt, metabolisiert in der folgenden Reaktion

$$
\begin{gather*}
\ce{C5H10O5(s) + 5 O2(g) -> 5 CO2(g) + 5 H2O(l)} \\
\Delta H\sub{metab,\mathnormal{n},Ribose}^{\circ} = -2348\,\small\kilojoulepermole.
\end{gather*}
$$

Die Metabolisierung von Zucker entspricht der thermischen Verbrennung mit Brennwert, da die Produkte in ihren Standardzustand überführt werden. Dadurch liegt das Wasser als Flüssigkeit vor und nicht als Dampf. 

### Lipide

Wir metabolisieren jetzt zuerst ein einfache Fettsäure, nämlich die Palmitinsäure. Die Palmitinsäure kommt in vielen Fetten vor, zum Beispiel in Palmöl, und ist damit eine der häufigsten Fettsäuren in der Nahrung. Sie hat die Summenformel $\ce{C16H32O2}$ und verbrennt nach der Reaktion

$$
\begin{gather*}
\ce{C16H32O2(s) + 48 O2(g) -> 16 CO2(g) + 16 H2O(l)} \\
\Delta H\sub{metab,\mathnormal{n},Palmitinsäure}^{\circ} = -10016\,\small\kilojoulepermole.
\end{gather*}
$$ {#eq-palmitic-combustion}

Eine weitere Fettsäure, die in der Nahrung vorkommt, ist die Ölsäure. Sie ist eine einfach ungesättigte Fettsäure, die in Olivenöl vorkommt. Sie hat die Summenformel $\ce{C18H34O2}$ und verbrennt nach der Reaktion

$$
\begin{gather*}
\ce{C18H34O2(s) + 51 O2(g) -> 18 CO2(g) + 17 H2O(l)} \\
\Delta H\sub{metab,\mathnormal{n},Ölsäure}^{\circ} = -11161\,\small\kilojoulepermole.
\end{gather*}
$$ {#eq-oleic-combustion}

Auch im Fall der Lipide entspricht die Metabolisierung der thermischen Verbrennung mit Brennwert. 

### Proteine

Proteine sind komplexer als Zucker und Lipide, da sie neben Kohlenstoff, Wasserstoff und Sauerstoff auch Stickstoff und Schwefel enthalten. Dadurch ist der Vergleich zwischen der thermischen Verbrennung und dem Stoffwechsel etwas komplizierter.

#### Stickstoff Ausscheidung im Urin

Betrachten wir die Aminosäure Alanin. Deren thermische Verbrennung würde so aussehen

$$
\begin{gather*}
\ce{2 C3H7NO2(s) + 15/2 O2(g) -> 6 CO2(g) + 7 H2O(l) + N2(g)} \\
\Delta H\sub{c,\mathnormal{n},Alanin}^{\circ} = -1621\,\small\kilojoulepermole.
\end{gather*}
$$ {#eq-thermal-ala-combustion}

In beiden Fällen kann die Reaktion in einem Bombenkalorimeter gestartet werden und dadurch wird am Ende abgekühlt, sodass alle Produkte in ihren Standardzustand vorliegen.

Eine Funktion des Urins ist die Ausscheidung von überschüssigem Stickstoff. Wir geben ja kein Stickstoffgas ab, sondern Harnstoff $\ce{CO(NH2)2}$. Der Harnstoff ist unter Standardbedingungen fest. In einer thermischen Verbrennung würde der Harnstoff auch zu seinen gasförmigen Bestandteilen zerlegt werden nach der Reaktion

$$
\begin{gather*}
\ce{CO(NH2)2(s) + 3/2 O2(g) -> CO2(g) + 2 H2O(l) + N2(g)} \\
\Delta H\sub{c,\mathnormal{n},Harnstoff}^{\circ} = -632\,\small\kilojoulepermole.
\end{gather*}
$$ {#eq-urea-combustion}

Das zeigt, welchen Energiegehalt wir durch den Urin verlieren. Das bedeutet aber auch, dass die Metabolisierung von Methionin in unserem Körper um einen gewissen Betrag verringert wird. Dieser Betrag muss ja nach Hess genau einer gewissen Menge verbrannten Harnstoff entsprechen. Welcher Betrag ist es denn?

In @eq-urea-combustion steht Harnstoff noch auf der Eduktseite. Wir bräuchten es aber auf der Produktseite, damit das unserem Stoffwechsel einigermassen entspricht. Dazu lassen wir die Reaktion aus @eq-urea-combustion einfach rückwärts laufen.

$$
\begin{gather*}
\ce{CO2(g) + 2 H2O(l) + N2(g) -> CO(NH2)2(s) + 3/2 O2(g)} \\
\Delta H\sub{Urin,\mathnormal{n}}^{\circ} = -\Delta H\sub{c,\mathnormal{n},Harnstoff}^{\circ} = +632\,\small\kilojoulepermole
\end{gather*}
$$ {#eq-urea-combustion-reverse}

Beachte das umgekehrte Vorzeichen der Enthalpie. Nun können wir @eq-thermal-met-combustion mit @eq-urea-combustion-reverse kombinieren, indem wir beide Gleichungen addieren. Wir haben gesagt, dass der Urin neben anderen Funktionen auch zur Stickstoffentsorgung genutzt wird. Wenn das die Vorgabe ist, dann müssen wir lediglich dafür sorgen, dass bei der Addition die entstandene Menge an $\ce{N2}$ aus @eq-thermal-met-combustion genau der Menge an $\ce{N2}$ aus @eq-urea-combustion-reverse entspricht. Das ist aber bereits in unserem Fall gegeben. Dann addieren wir einfach beide Gleichungen und erhalten

$$
\begin{gather*}
\ce{2 C3H7NO2(s) + 15/2 O2(g) + CO2(g) + 2 H2O(l) + N2(g) ->} \\
\ce{6 CO2(g) + 7 H2O(l) + N2(g) + CO(NH2)2(s) + 3/2 O2(g)}.
\end{gather*}
$$

Wir haben keine Angst vor den vielen chemischen Summenformeln und den Zahlen. Denn jetzt kürzen wir und erhalten

$$
\begin{gather*}
\ce{2 C5H11NO2S(s) + 12/2 O2(g) ->} \\
\ce{5 CO2(g) + 5 H2O(l) + CO(NH2)2(s)}
\end{gather*}
$$ {#eq-metabolic-met-combustion-subtraction}

Bleibt nur noch übrig, die Enthalpien zu addieren. Das ist aber auch ganz einfach, da die Enthalpie eine Zustandsfunktion ist und wir das Hess'sche Gesetz anwenden. 

$$
\begin{split}
\Delta H\sub{metab,\mathnormal{n},Alanin}^{\circ} 
    &= \Delta H\sub{c,\mathnormal{n},Alanin}^{\circ} + \Delta H\sub{Urin,\mathnormal{n}}^{\circ} \\
    &= -1621\,\small\kilojoulepermole + 632\,\small\kilojoulepermole \\
    &= -989\,\small\kilojoulepermole.
\end{split}
$$

Wenn wir also Alanin in unserem Körper metabolisieren, dann gewinnen wir $-2932\,\kilojoulepermole$ an Energie, was deutlich weniger ist als die Energie, die wir durch die thermische Verbrennung von Methionin gewinnen würden. Das liegt daran, dass wir den Stickstoff nicht in Form von gasförmigem Stickstoff sondern in Form von Harnstoff ausscheiden.

#### Schwefel Ausscheidung im Urin

Die Aminosäure Methionin besitzt sogar eine Thiolgruppe und damit auch Schwefel. Wenn wir Methionin thermisch verbrennen würden, dann müsste die Reaktion so aussehen

$$
\begin{gather*}
\ce{2 C5H11NO2S(s) + 31/2 O2(g) ->} \\
\ce{10 CO2(g) + 11 H2O(l) + N2(g) + 2 SO2(g)}
\end{gather*}
$$ {#eq-thermal-met-combustion}

Allerdings wird in der kalorimetrischen Messung von Verbrennungsenthalpien von schwefelhaltigen Verbindungen nicht das Schwefeldioxid als Endprodukt gemessen, sondern die Schwefelsäure. Um die tatsächliche thermische Verbrennungsenthalpie von Methionin zu bestimmen, müssen wir @eq-sulfuric-acid-from-sulfur-dioxide von der obigen Gleichung subtrahieren. Das geschieht indem man @eq-sulfuric-acid-from-sulfur-dioxide ugedreht dazu addiert. Dabei muss die Anzahl der $\ce{SO2}$ Moleküle angepasst werden. Daraus ergibt sich die Gesamtreaktion

$$
\begin{gather*}
\ce{2 C5H11NO2S(s) + 31/2 O2(g) + 2 SO2(g) + O2(g) + 2 H2O(l) ->} \\
\ce{10 CO2(g) + 11 H2O(l) + N2(g) + 2 SO2(g) + 2 H2SO4(aq)}
\end{gather*}
$$

Nach Kürzen der Substanzen, die auf beiden Seiten gleich sind, erhalten wir

$$
\begin{gather*}
\ce{2 C5H11NO2S(s) + 35/2 O2(g) ->} \\
\ce{10 CO2(g) + 9 H2O(l) + N2(g) + 2 H2SO4(aq)}.
\end{gather*}   
$$ {#eq-calorimetric-met-combustion}

Wenn also Verbrennungsenthalpien von Aminosäuren bestimmt und angegeben werden, dann wurde die Verbrennung so gefahren, dass Schwefelsäure als Endprodukt entstand. Im Falle von Methionin beträgt die angegebene Verbrennungsenthalpie $\Delta H_{\text{kalorimeter},n,\text{Met}} = -3564\,\small\kilojoulepermole$. Dadurch ist die wahre Verbrennungsenthalpie von Methionin nach @eq-thermal-met-combustion

$$
\begin{split}
\Delta H_{\text{therm},n,\text{Met}} &= \Delta H_{\text{kalorimeter},n,\text{Met}} - 2 \cdot \Delta H_{\text{r},n}^{\circ}\left(\ce{H2SO4}\right) \\
&= -3564\,\small\kilojoulepermole - 2 \cdot (-273\,\small\kilojoulepermole) \\
&= -3018\,\small\kilojoulepermole.
\end{split}
$$

Der Großteil des Schwefel wird im Urin als Sulfat ausgeschieden^[Es gibt andere Ausscheidungsmechanismen, die zu anderen Schwefelverbindungen führen. Wir konzentrieren uns allerdings auf den Sulfatweg, weil er in Tieren durchaus oft vorkommt. Zum Beispiel wurde festgestellt, dass der Großteil des Schwefels im Urin fast bis 90% als Sulfat ausgeschieden wird.]. Dadurch entspricht die angegebene kalorimetrische Verbrennungsenthalpie von Methionin bis auf den Harnstoff, fast der metabolischen Verbrennung von Methionin. Um die metabolische Verbrennung von Methionin zu bestimmen, müssen wir noch lediglich die Enthalpie der umgekehrten Harnstoffverbrennung addieren. Das tun wir gleich der @eq-calorimetric-met-combustion an und erhalten

$$
\begin{gather*}
\ce{2 C5H11NO2S(s) + 35/2 O2(g) + CO2(g) + 2 H2O(l) + N2(g) ->} \\
\ce{10 CO2(g) + 9 H2O(l) + N2(g) + 2 H2SO4(aq) + CO(NH2)2(s) + 3/2 O2(g)}.
\end{gather*}
$$

Durch Kürzen der Substanzen, die auf beiden Seiten gleich sind, bekommen wir

$$
\begin{gather*}
\ce{2 C5H11NO2S(s) + 16 O2(g) ->} \\
\ce{9 CO2(g) + 7 H2O(l) + 2 H2SO4(aq) + CO(NH2)2(s)}.
\end{gather*}
$$ {#eq-metab-met-combustion}

Diese Reaktion hat folgende Standardenthalpie

$$
\begin{split}
\Delta H_{\text{metab},n,\text{Met}}^{\circ} 
    &= \Delta H_{\text{kalorimeter},n,\text{Met}} + \Delta H_{\text{Urin},n}^{\circ} \\
    &= -3564\,\small\kilojoulepermole + 632\,\small\kilojoulepermole \\
    &= -2932\,\small\kilojoulepermole.
\end{split}
$$

Beachte bei der Metabolisierung von schwefelhaltigen Substanzen folgendes:

- Die angegebenen Verbrennungsenthalpien von schwefelhaltigen Substanzen entsprechen nicht der Verbrennung zu Schwefeldioxid, sondern der Verbrennung zu Schwefelsäure^[Das sollte jedoch im Einzelfall immer nachgeprüft werden].
- Dadurch muss lediglich die Enthalpie der umgekehrten Harnstoffverbrennung zu der angegebenen Verbrennungsenthalpie addiert werden, um die metabolische Verbrennung zu erhalten.
- Die tatsächliche thermische Verbrennung von schwefelhaltigen Substanzen ist um die Bildung von Schwefelsäure weniger exotherm.

### Energie im Metabolismus

Der Metabolismus lässt sich ganz gut mit Standardenthalpien beschreiben. Da wo eine grössere Genauigkeit notwendig ist, können die thermodynamischen Werte für die jeweilige Körpertemperatur benutzt werden statt $T = 298\,\kelvin$. Die allgemeine Gleichung beim Abbau von Biomasse, oder Nahrung, ist ähnlich @eq-biomass-combustion mit den notwendigen Anpassungen beim Abbau:

$$
\begin{gather*}
\ce{{Biomasse} + x O2(g) ->} \\
\ce{a CO2(g) + b H2O(l) + c CO(NH2)2(g) + d H2SO4(g)}.
\end{gather*}
$$ {#eq-biomass-metabolization}

Die dazugehörig molare Enthalpie ist dieselbe, wie bei der technischen Verbrennung und schreibt sich

$$
\Delta H_{\text{metab},n}^{\circ} = \Delta U_{\text{metab},n} - p \Delta V_n.
$$

Vergiss nicht; die Enthalpie ist diejenige Energie, die bei konstantem Druck verwendbar wird. Sie ergibt sich aus der inneren Energie abzüglich der Expansionsarbeit, die die beteiligten Gase bedingen. Dabei ist der Druck $p = 101325\,\pascal$ und die Temperatur $T = 298\,\kelvin$ und stellen somit Standardbedingungen dar. Dadurch ist das molare Volumen $V_n = 0.0245\cubicmeterpermole$ bei Annahme eines perfekten Gases. 

Die molare Enthalpie ist so definiert

$$
\Delta H_{\text{metab}, n}^{\circ} = \frac{\Delta H_{\text{metab},n}^{\circ}}{n},
$$

sodass die Gesamtenthalpie einer metabolischen Abbaureaktion von Biomasse

$$
\Delta H_{\text{metab}}^{\circ} = n \cdot \Delta H_{\text{metab},n}^{\circ}
$$ {#eq-molar-enthalpy-def}

wäre. Weiterhin kann hieraus die im Alltag viel praktischere massenbezogene Enthalpie abgeleitet werden. Wir teilen @eq-molar-enthalpy-def durch die gegebene Masse $m$ und erhalten

$$
\frac{\Delta H_{\text{metab}}^{\circ}}{m} = \frac{n \cdot \Delta H_{\text{metab},n}^{\circ}}{m}.
$$ {#eq-mass-enthalpy-step}

Auf der linken Seite befindet sich bereits die Definition der auf Masse bezogenen Enthalpie $\Delta H_{\text{metab},m}^{\circ}$. Die werden wir dort auch gleich einsetzen. Da die Masse $m$ einer Substanz, sich aus dem Produkt der Stoffmenge $n$ und der molarer Masse $M$ ergibt $m = n \cdot M$, können wir für den Quotienten aus Stoffmenge und Masse folgendes schreiben:

$$
\frac{n}{m} = \frac{1}{M}.
$$

Wenn wir das in @eq-mass-enthalpy-step einsetzen bekommen wir

$$
\Delta H_{\text{metab},m}^{\circ} = \frac{\Delta H_{\text{metab},n}^{\circ}}{M}.
$$ {#eq-mass-enthalpy-def}

So können wir bei einer bekannten Substanz ohne Mühen die massenbezogene Metabolisierungsenergie berechnen.

### Respiratorischer Quotient

Betrachten wir das bei einer Verbrennung oder Metabolisierung verbrauchte Volumen an Sauerstoff. Wir können das leicht aus der Stoffmenge $n$ und dem molaren Volumen $V_n$ berechnen. Das verbrauchte Volumen an Sauerstoff ist

$$
V_{\ce{O2}} = n_{\ce{O2}} \cdot V_n.
$$

Das entstandene Volumen an Kohlendioxid ist

$$
V_{\ce{CO2}} = n_{\ce{CO2}} \cdot V_n.
$$

Dadurch können wir das Verhältnis aus entstandenem Kohlendioxid zu verbrauchtem Sauerstoff bestimmen. Dieses Verhältnis nennen wir den **respiratorischen Quotienten** $\mathrm{RQ}$ und berechnet sich wie folgt:

$$
\mathrm{RQ} = \frac{V_{\ce{CO2}}}{V_{\ce{O2}}} = \frac{n_{\ce{CO2}}}{n_{\ce{O2}}}.
$$

Der respiratorische Quotient ist eine wichtige Kenngrösse, um die Art der verstoffwechselten Nährstoffe zu bestimmen. Der $\mathrm{RQ}$ wird zum Beispiel für die Bestimmung des Grundumsatzes verwendet, um zu bestimmen, ob mehr Kohlenhydrate oder mehr Fette verstoffwechselt werden. Daneben kann der $\mathrm{RQ}$ auch für die Bestimmung von Stoffwechselstörungen, die Überwachung von Patienten auf der Intensivstation, und in der Sportmedizin zur Leistungsdiagnostik genutzt werden. 
